manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      path: firmware/zmk  # パスを変更して競合を回避
      import: app/west.yml
  self:
    path: config  # マニフェストリポジトリのパス
