name: Build ZMK firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Init west and update
        run: |
          pip3 install --user west
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          west init -l config
          west update
          west zephyr-export
          pip3 install -r zephyr/scripts/requirements.txt

      - name: Build firmware
        run: |
          west build -s app -b nice_nano_v2 -- -DSHIELD=myboard

      - name: Upload UF2
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/zephyr/zmk.uf2

