name: Build ZMK Firmware

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install west
        run: pip3 install --user west

      - name: Initialize west
        run: west init -l config

      - name: Update west modules
        run: west update

      - name: Export Zephyr CMake
        run: west zephyr-export

      - name: Build firmware
        run: |
          west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=myboard
          ls -al build/zephyr/

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/zephyr/zmk.uf2

