on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      # Use the 'include' input to specify your board and shield
      # This is an array, so you can list multiple configurations if needed
      config: |
        - board: nice_nano_v2
          shield: myboard
