name: Build ZMK Firmware

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          clean: true

      - name: Clean workspace
        run: |
          rm -rf .west
          rm -rf firmware

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git cmake ninja-build gperf ccache dfu-util wget \
            device-tree-compiler python3-pip python3-setuptools python3-wheel \
            xz-utils file make gcc g++
          pip3 install --user west
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure ccache
        run: |
          echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV
          ccache --max-size=1G

      - name: Initialize west
        run: |
          west init -l config
          west update
          west zephyr-export

      - name: Build firmware
        run: |
          west build -s zmk/app -b nice_nano_v2 -- \
            -DSHIELD=myboard \
            -DZMK_CONFIG="$(pwd)/config"
          ccache --show-stats

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/zephyr/zmk.uf2
          if-no-files-found: error

      - name: Debug on failure
        if: failure()
        run: |
          find . -name "build.log" -exec cat {} \;
          west --version
          ls -R config
