name: Build ZMK

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout config
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build gperf ccache dfu-util dtc wget python3-pip

      - name: Install west
        run: pip install --upgrade west

      - name: Init and update west
        run: |
          west init -l config
          west update
          west zephyr-export

      - name: Build firmware
        run: |
          west build -s app -b nice_nano_v2 -d build -- -DSHIELD=myboard
